# Here we are going to sample unique set of points to generate data

1. Number of data to be generated is 20000 new unique user
2. Number of places to be visited is

In [1]:
import pandas as pd
df = pd.read_csv("processedTMSC2014.tsv",sep='\t', engine="python")
df.drop(["Unnamed: 0"],axis=1, inplace=True)

In [2]:
df

,User ID (anonymized),Venue ID (Foursquare),Venue category ID (Foursquare),Venue category name (Fousquare),Latitude,Longitude,Timezone offset(minutes),UTC time,Status,Iteration,InfectorId,InfectionTime,Time
0,470,49bbd6c0f964a520f4531fe3,4bf58dd8d48988d127951735,Arts & Crafts Store,40.719810,-74.002581,-240,Tue Apr 03 18:00:09 +0000 2012,0,0,0,0,1333476009
1,979,4a43c0aef964a520c6a61fe3,4bf58dd8d48988d1df941735,Bridge,40.606800,-74.044170,-240,Tue Apr 03 18:00:25 +0000 2012,0,0,0,0,1333476025
2,69,4c5cc7b485a1e21e00d35711,4bf58dd8d48988d103941735,Home (private),40.716162,-73.883070,-240,Tue Apr 03 18:02:24 +0000 2012,0,0,0,0,1333476144
3,395,4bc7086715a7ef3bef9878da,4bf58dd8d48988d104941735,Medical Center,40.745164,-73.982519,-240,Tue Apr 03 18:02:41 +0000 2012,0,0,0,0,1333476161
4,87,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck,40.740104,-73.989658,-240,Tue Apr 03 18:03:00 +0000 2012,0,0,0,0,1333476180
...,...,...,...,...,...,...,...,...,...,...,...,...,...
227423,688,3fd66200f964a52000e71ee3,4bf58dd8d48988d1e7931735,Music Venue,40.733596,-74.003139,-300,Sat Feb 16 02:29:11 +0000 2013,0,0,0,0,1360981751
227424,560,4bca32ff0687ef3be789dbcc,4bf58dd8d48988d16c941735,Burger Joint,40.745719,-73.993720,-300,Sat Feb 16 02:31:35 +0000 2013,0,0,0,0,1360981895
227425,945,50a77716e4b0b5a9492f6f56,4bf58dd8d48988d103941735,Home (private),40.854364,-73.883070,-300,Sat Feb 16 02:33:16 +0000 2013,0,0,0,0,1360981996
227426,671,4514efe0f964a520e7391fe3,4bf58dd8d48988d11d941735,Bar,40.735981,-74.029309,-300,Sat Feb 16 02:34:31 +0000 2013,0,0,0,0,1360982071
227427,942,4a1e0ca0f964a520bf7b1fe3,4bf58dd8d48988d116941735,Bar,40.726805,-73.957422,-300,Sat Feb 16 02:35:36 +0000 2013,0,0,0,0,1360982136

In [3]:
#####################################################
## HOW MANY UNIQUE USERS ARE THERE?                ##
#####################################################
unique_users =  pd.unique(df["User ID (anonymized)"])
max(unique_users)
## Make the userIds after the maximum unique_users ##

1083

# What do we need to sample i.e. what fields?

1. User ID (anonymized)
2. Latitude Longitude (tuples only because it means a place)
3. UTC Time (Or matter of fact we use time because anyway we are converting UTC Time to epoch)

In [4]:
df.columns

Index(['User ID (anonymized)', 'Venue ID (Foursquare)',
       'Venue category ID (Foursquare)', 'Venue category name (Fousquare)',
       'Latitude', 'Longitude', 'Timezone offset(minutes)', 'UTC time',
       'Status', 'Iteration', 'InfectorId', 'InfectionTime', 'Time'],
      dtype='object')

In [5]:
#df[['Venue ID (Foursquare)','Venue category ID (Foursquare)', 'Venue category name (Fousquare)','Latitude', 'Longitude', 'UTC time','Time']]

In [6]:
#####################################################
## HOW MANY UNIQUE CHECKINS ARE THERE?             ##
#####################################################
unique_checkins = df[['Venue ID (Foursquare)','Venue category ID (Foursquare)', 'Venue category name (Fousquare)','Latitude', 'Longitude', 'UTC time','Time']]
#unique_checkins
unique_checkins = unique_checkins.values.tolist()
numberOfCheckins = len(unique_checkins)
len(unique_checkins)

227428

In [7]:
# SAMPLE FROM UNIQUE CHECKINS
# Maximum range is equal to the number of userIds
import time
from random import randrange
new_dataframe = pd.DataFrame()
number_of_users = 50

# Non - Multithreading code starts here

In [8]:
###############################################################
##  BELOW IS CODE WITHOUT MULTITHREADING (UNCOMMENT TO USE)  ##
###############################################################

#for i in range(1,number_of_users):
#    #How many checkin do we want for this user?
#    user_checkin_number = randrange(35,65)
#    #Generating checkin for the user
#    t0 = time.clock()
#    for j in range(user_checkin_number):
#        #Sampling the checkin from the checkins that we have originally
#        sampled_checkin = unique_checkins[randrange(0,227164)]
#        #Making a row to append later to dataframe
#        new_row = {'User ID (anonymized)':i,'Venue ID (Foursquare)':sampled_checkin[0],'Venue category ID (Foursquare)':sampled_checkin[1], 'Venue category name (Fousquare)':sampled_checkin[2],'Latitude':sampled_checkin[3], 'Longitude':sampled_checkin[4], 'UTC time':sampled_checkin[5],'Time':sampled_checkin[6]}
#        #new_row = {'User ID (anonymized)':i,'Venue category ID (Foursquare)':sampled_checkin[0],'Latitude':sampled_checkin[1],'Longitude':sampled_checkin[2],'UTC time':sampled_checkin[3],'Time':sampled_checkin[4]}
#        new_dataframe = new_dataframe.append(new_row, ignore_index=True)
#    t1 = time.clock()
#    print(f"Data added for user number: {i} and numbered: {user_checkin_number} and time {t1-t0} seconds.")

In [9]:
##  BELOW IS CODE WITHOUT MULTITHREADING (UNCOMMENT TO USE)  ##

#new_dataframe

In [10]:
##  BELOW IS CODE WITHOUT MULTITHREADING (UNCOMMENT TO USE)  ##

#new_dataframe = new_dataframe.sort_values(by=['Time'], ascending=True)
#new_dataframe

In [11]:
##  BELOW IS CODE WITHOUT MULTITHREADING (UNCOMMENT TO USE)  ##

#new_dataframe.to_csv("newDataSet.tsv", sep="\t")

# Multithreading code starts here

In [12]:
# SAMPLE FROM UNIQUE CHECKINS
# Maximum range is equal to the number of userIds
import threading 
lock = threading.Lock()
new_dataframe = pd.DataFrame()

In [13]:
def add_checkins(userStartId,numberOfUsers):
    global new_dataframe
    global unique_checkins
    global lock
    for userid in range(userStartId, userStartId+numberOfUsers):
        #How many checkin do we want for this user?
        user_checkin_number = randrange(35,65)
        #Generating checkin for the user
        t0 = time.clock()
        for j in range(user_checkin_number):
            #Sampling the checkin from the checkins that we have originally
            sampled_checkin = unique_checkins[randrange(0,227164)]
            #Making a row to append later to dataframe
            new_row = {'User ID (anonymized)':userid,'Venue ID (Foursquare)':sampled_checkin[0],'Venue category ID (Foursquare)':sampled_checkin[1], 'Venue category name (Fousquare)':sampled_checkin[2],'Latitude':sampled_checkin[3], 'Longitude':sampled_checkin[4], 'UTC time':sampled_checkin[5],'Time':sampled_checkin[6]}
            lock.acquire()
            new_dataframe = new_dataframe.append(new_row, ignore_index=True)
            lock.release()
        t1 = time.clock()
        print(f"Data added for user number: {userid} and numbered: {user_checkin_number} and time {t1-t0} seconds.")
t0 = time.clock()

number_of_users = 1000
number_of_threads = 4
users_per_thread = int(number_of_users / number_of_threads)

threads = [threading.Thread(target=add_checkins, args=(users_per_thread*i+1,users_per_thread)) for i in range(number_of_threads)]
[thrd.start() for thrd in threads]
[thrd.join() for thrd in threads]
print(f"Time taken: {time.clock() - t0} seconds")

/home/mayuresh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/mayuresh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  if __name__ == '__main__':
/home/mayuresh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead

Data added for user number: 1 and numbered: 46 and time 1.2021170000000003 seconds.
Data added for user number: 501 and numbered: 51 and time 1.8516410000000008 seconds.
Data added for user number: 2 and numbered: 48 and time 1.1873739999999993 seconds.
Data added for user number: 751 and numbered: 46 and time 2.407018 seconds.
Data added for user number: 251 and numbered: 63 and time 2.6784939999999997 seconds.
Data added for user number: 3 and numbered: 58 and time 1.0399340000000006 seconds.
Data added for user number: 502 and numbered: 63 and time 1.913813000000001 seconds.
Data added for user number: 252 and numbered: 57 and time 1.1995839999999998 seconds.
Data added for user number: 4 and numbered: 37 and time 1.1897590000000005 seconds.
Data added for user number: 503 and numbered: 38 and time 0.8850709999999999 seconds.
Data added for user number: 253 and numbered: 48 and time 1.891767999999999 seconds.
Data added for user number: 752 and numbered: 64 and time 3.5441839999999996 seconds.
Data added for user number: 504 and numbered: 46 and time 1.8039989999999992 seconds.
Data added for user number: 505 and numbered: 35 and time 0.6554079999999995 seconds.
Data added for user number: 254 and numbered: 49 and time 1.403364999999999 seconds.
Data added for user number: 5 and numbered: 52 and time 2.822789 seconds.
Data added for user number: 753 and numbered: 36 and time 1.7096909999999994 seconds.
Data added for user number: 6 and numbered: 48 and time 1.039275 seconds.
Data added for user number: 255 and numbered: 61 and time 1.7112170000000013 seconds.
Data added for user number: 506 and numbered: 55 and time 1.8665219999999998 seconds.
Data added for user number: 754 and numbered: 45 and time 1.6886320000000001 seconds.
Data added for user number: 7 and numbered: 39 and time 1.4829969999999992 seconds.
Data added for user number: 755 and numbered: 41 and time 1.0082179999999994 seconds.
Data added for user number: 256 and numbered: 37 and time 1.771397000000002 seconds.
Data added for user number: 507 and numbered: 55 and time 2.5509570000000004 seconds.
Data added for user number: 8 and numbered: 58 and time 1.774880999999997 seconds.
Data added for user number: 257 and numbered: 56 and time 1.8647489999999998 seconds.
Data added for user number: 756 and numbered: 64 and time 2.610797999999999 seconds.
Data added for user number: 9 and numbered: 59 and time 1.6606740000000002 seconds.
Data added for user number: 508 and numbered: 54 and time 1.982444000000001 seconds.
Data added for user number: 258 and numbered: 44 and time 1.5477169999999987 seconds.
Data added for user number: 259 and numbered: 40 and time 0.6886489999999981 seconds.
Data added for user number: 757 and numbered: 61 and time 1.8165179999999985 seconds.
Data added for user number: 10 and numbered: 48 and time 1.7062910000000002 seconds.
Data added for user number: 509 and numbered: 41 and time 2.4538399999999996 seconds.
Data added for user number: 260 and numbered: 38 and time 1.3751840000000009 seconds.
Data added for user number: 758 and numbered: 41 and time 1.4586289999999984 seconds.
Data added for user number: 11 and numbered: 43 and time 1.8699390000000022 seconds.
Data added for user number: 510 and numbered: 45 and time 1.613854 seconds.
Data added for user number: 759 and numbered: 52 and time 1.556051 seconds.
Data added for user number: 511 and numbered: 61 and time 1.1927219999999998 seconds.
Data added for user number: 261 and numbered: 37 and time 2.7823850000000014 seconds.
Data added for user number: 262 and numbered: 48 and time 0.8667859999999976 seconds.
Data added for user number: 12 and numbered: 53 and time 2.8416780000000017 seconds.
Data added for user number: 760 and numbered: 59 and time 2.209060000000001 seconds.
Data added for user number: 13 and numbered: 53 and time 1.1096059999999994 seconds.
Data added for user number: 263 and numbered: 47 and time 1.2997180000000021 seconds.
Data added for user number: 512 and numbered: 37 and time 2.3249369999999985 seconds.
Data added for user number: 264 and numbered: 38 and time 1.0392200000000003 seconds.
Data added for user number: 14 and numbered: 56 and time 1.2796650000000014 seconds.
Data added for user number: 761 and numbered: 44 and time 2.8501900000000013 seconds.
Data added for user number: 513 and numbered: 48 and time 2.635162000000001 seconds.
Data added for user number: 762 and numbered: 48 and time 1.655149999999999 seconds.
Data added for user number: 265 and numbered: 51 and time 2.4884850000000007 seconds.
Data added for user number: 15 and numbered: 61 and time 2.855373 seconds.
Data added for user number: 514 and numbered: 38 and time 1.6264619999999965 seconds.
Data added for user number: 16 and numbered: 46 and time 1.219109999999997 seconds.
Data added for user number: 266 and numbered: 63 and time 1.9368760000000016 seconds.
Data added for user number: 763 and numbered: 63 and time 3.1054630000000003 seconds.
Data added for user number: 515 and numbered: 47 and time 2.3360799999999955 seconds.
Data added for user number: 267 and numbered: 60 and time 1.4538900000000012 seconds.
Data added for user number: 17 and numbered: 43 and time 3.0562200000000033 seconds.
Data added for user number: 764 and numbered: 63 and time 1.713245999999998 seconds.
Data added for user number: 268 and numbered: 55 and time 1.6042699999999996 seconds.
Data added for user number: 516 and numbered: 61 and time 2.3855919999999955 seconds.
Data added for user number: 765 and numbered: 46 and time 1.7519239999999954 seconds.
Data added for user number: 269 and numbered: 45 and time 1.9527140000000003 seconds.
Data added for user number: 18 and numbered: 56 and time 2.546140000000001 seconds.
Data added for user number: 517 and numbered: 63 and time 2.106111999999996 seconds.
Data added for user number: 518 and numbered: 41 and time 1.0686569999999946 seconds.
Data added for user number: 270 and numbered: 51 and time 2.283407000000004 seconds.
Data added for user number: 766 and numbered: 63 and time 2.8979770000000045 seconds.
Data added for user number: 19 and numbered: 64 and time 2.409973000000001 seconds.
Data added for user number: 519 and numbered: 55 and time 2.408850000000001 seconds.
Data added for user number: 767 and numbered: 60 and time 2.082098000000002 seconds.
Data added for user number: 271 and numbered: 54 and time 2.6546769999999995 seconds.
Data added for user number: 20 and numbered: 61 and time 2.609460999999996 seconds.
Data added for user number: 520 and numbered: 47 and time 2.301231999999999 seconds.
Data added for user number: 272 and numbered: 48 and time 1.6708209999999966 seconds.
Data added for user number: 21 and numbered: 37 and time 1.315217000000004 seconds.
Data added for user number: 521 and numbered: 35 and time 1.7134849999999986 seconds.
Data added for user number: 768 and numbered: 61 and time 3.6895349999999993 seconds.
Data added for user number: 22 and numbered: 44 and time 1.631902999999994 seconds.
Data added for user number: 273 and numbered: 60 and time 2.553543000000005 seconds.
Data added for user number: 769 and numbered: 45 and time 1.7149789999999996 seconds.
Data added for user number: 23 and numbered: 63 and time 2.407595999999998 seconds.
Data added for user number: 522 and numbered: 47 and time 2.713788000000001 seconds.
Data added for user number: 274 and numbered: 40 and time 1.9654699999999963 seconds.
Data added for user number: 770 and numbered: 40 and time 1.746852000000004 seconds.
Data added for user number: 275 and numbered: 46 and time 1.4568079999999952 seconds.
Data added for user number: 771 and numbered: 52 and time 1.7099740000000025 seconds.
Data added for user number: 24 and numbered: 57 and time 2.8741039999999956 seconds.
Data added for user number: 523 and numbered: 50 and time 2.810279999999999 seconds.
Data added for user number: 276 and numbered: 46 and time 2.001114000000001 seconds.
Data added for user number: 524 and numbered: 46 and time 1.0444249999999968 seconds.
Data added for user number: 25 and numbered: 37 and time 1.8074979999999954 seconds.
Data added for user number: 277 and numbered: 35 and time 0.8687940000000012 seconds.

Data added for user number: 772 and numbered: 51 and time 2.6590570000000042 seconds.
Data added for user number: 525 and numbered: 44 and time 2.3652019999999965 seconds.
Data added for user number: 26 and numbered: 50 and time 1.937342000000001 seconds.
Data added for user number: 278 and numbered: 54 and time 1.9493849999999995 seconds.
Data added for user number: 279 and numbered: 47 and time 1.3612269999999995 seconds.
Data added for user number: 526 and numbered: 50 and time 1.8474540000000061 seconds.
Data added for user number: 773 and numbered: 58 and time 3.7708140000000014 seconds.
Data added for user number: 527 and numbered: 58 and time 1.532817999999999 seconds.
Data added for user number: 27 and numbered: 45 and time 3.1896440000000013 seconds.
Data added for user number: 528 and numbered: 41 and time 0.9292579999999973 seconds.
Data added for user number: 280 and numbered: 60 and time 2.6564669999999992 seconds.
Data added for user number: 529 and numbered: 48 and time 1.580131999999999 seconds.
Data added for user number: 774 and numbered: 54 and time 3.7068379999999976 seconds.
Data added for user number: 281 and numbered: 61 and time 2.4577000000000027 seconds.
Data added for user number: 775 and numbered: 41 and time 0.8966970000000032 seconds.
Data added for user number: 28 and numbered: 50 and time 4.477103999999997 seconds.
Data added for user number: 530 and numbered: 58 and time 2.088884 seconds.
Data added for user number: 29 and numbered: 43 and time 0.9420989999999989 seconds.
Data added for user number: 531 and numbered: 59 and time 1.9989889999999946 seconds.
Data added for user number: 776 and numbered: 42 and time 2.6872320000000016 seconds.
Data added for user number: 30 and numbered: 47 and time 2.1730039999999917 seconds.
Data added for user number: 282 and numbered: 62 and time 4.755333 seconds.
Data added for user number: 532 and numbered: 56 and time 1.8978440000000063 seconds.
Data added for user number: 31 and numbered: 37 and time 1.714585999999997 seconds.
Data added for user number: 283 and numbered: 52 and time 1.8965920000000125 seconds.
Data added for user number: 777 and numbered: 47 and time 3.6015780000000035 seconds.
Data added for user number: 533 and numbered: 47 and time 2.3184870000000046 seconds.
Data added for user number: 32 and numbered: 49 and time 2.472038999999995 seconds.
Data added for user number: 778 and numbered: 43 and time 1.9380529999999965 seconds.
Data added for user number: 284 and numbered: 63 and time 2.5179760000000044 seconds.
Data added for user number: 534 and numbered: 40 and time 1.8590769999999992 seconds.
Data added for user number: 779 and numbered: 60 and time 2.231495999999993 seconds.
Data added for user number: 33 and numbered: 60 and time 3.087294 seconds.
Data added for user number: 780 and numbered: 36 and time 1.2798349999999914 seconds.
Data added for user number: 285 and numbered: 64 and time 3.290495000000007 seconds.
Data added for user number: 535 and numbered: 51 and time 4.30311300000001 seconds.
Data added for user number: 34 and numbered: 48 and time 2.1577740000000034 seconds.
Data added for user number: 286 and numbered: 44 and time 2.4069140000000004 seconds.
Data added for user number: 35 and numbered: 47 and time 1.3211330000000032 seconds.
Data added for user number: 781 and numbered: 43 and time 3.5187099999999987 seconds.
Data added for user number: 287 and numbered: 38 and time 1.0355849999999975 seconds.
Data added for user number: 536 and numbered: 52 and time 2.887026000000006 seconds.
Data added for user number: 782 and numbered: 49 and time 1.3703160000000025 seconds.
Data added for user number: 288 and numbered: 46 and time 1.7805249999999972 seconds.
Data added for user number: 36 and numbered: 56 and time 2.9329740000000015 seconds.
Data added for user number: 289 and numbered: 55 and time 1.3140549999999962 seconds.
Data added for user number: 537 and numbered: 43 and time 2.5765790000000095 seconds.
Data added for user number: 783 and numbered: 42 and time 2.691247000000004 seconds.
Data added for user number: 290 and numbered: 40 and time 1.3387499999999903 seconds.
Data added for user number: 37 and numbered: 53 and time 3.090800999999999 seconds.
Data added for user number: 784 and numbered: 37 and time 1.434277999999992 seconds.
Data added for user number: 291 and numbered: 55 and time 1.7996930000000049 seconds.
Data added for user number: 538 and numbered: 52 and time 3.23285700000001 seconds.
Data added for user number: 38 and numbered: 43 and time 2.291780000000003 seconds.
Data added for user number: 785 and numbered: 61 and time 3.074386000000004 seconds.
Data added for user number: 292 and numbered: 49 and time 2.2908369999999962 seconds.
Data added for user number: 39 and numbered: 55 and time 1.8522970000000072 seconds.
Data added for user number: 539 and numbered: 40 and time 2.9618870000000044 seconds.
Data added for user number: 293 and numbered: 53 and time 2.026932000000002 seconds.
Data added for user number: 786 and numbered: 40 and time 2.1161749999999984 seconds.
Data added for user number: 40 and numbered: 49 and time 2.515765000000002 seconds.
Data added for user number: 41 and numbered: 40 and time 0.7528779999999955 seconds.
Data added for user number: 294 and numbered: 37 and time 1.9881749999999982 seconds.
Data added for user number: 540 and numbered: 64 and time 3.4307390000000026 seconds.
Data added for user number: 787 and numbered: 48 and time 2.8511280000000028 seconds.
Data added for user number: 541 and numbered: 62 and time 2.3850790000000046 seconds.
Data added for user number: 295 and numbered: 42 and time 2.692335 seconds.
Data added for user number: 42 and numbered: 61 and time 2.9481430000000017 seconds.
Data added for user number: 788 and numbered: 42 and time 2.174771000000007 seconds.
Data added for user number: 542 and numbered: 47 and time 1.8078079999999943 seconds.
Data added for user number: 296 and numbered: 42 and time 1.8501839999999987 seconds.
Data added for user number: 43 and numbered: 44 and time 1.9644820000000038 seconds.
Data added for user number: 789 and numbered: 40 and time 2.7802099999999967 seconds.
Data added for user number: 44 and numbered: 38 and time 2.1217120000000023 seconds.
Data added for user number: 297 and numbered: 50 and time 2.7196799999999968 seconds.
Data added for user number: 543 and numbered: 60 and time 2.871691999999996 seconds.
Data added for user number: 790 and numbered: 59 and time 2.2045379999999994 seconds.
Data added for user number: 298 and numbered: 42 and time 1.820295999999999 seconds.
Data added for user number: 45 and numbered: 36 and time 2.2181250000000006 seconds.
Data added for user number: 544 and numbered: 64 and time 3.3613530000000083 seconds.
Data added for user number: 299 and numbered: 47 and time 2.1112760000000037 seconds.
Data added for user number: 46 and numbered: 51 and time 2.021087999999992 seconds.
Data added for user number: 791 and numbered: 58 and time 3.6506490000000014 seconds.
Data added for user number: 545 and numbered: 39 and time 1.8022339999999986 seconds.
Data added for user number: 792 and numbered: 49 and time 1.2286900000000003 seconds.
Data added for user number: 300 and numbered: 48 and time 2.2725520000000046 seconds.
Data added for user number: 546 and numbered: 50 and time 1.3766689999999926 seconds.
Data added for user number: 47 and numbered: 55 and time 3.5056129999999968 seconds.
Data added for user number: 301 and numbered: 44 and time 2.3481490000000065 seconds.
Data added for user number: 547 and numbered: 47 and time 2.1723970000000037 seconds.
Data added for user number: 48 and numbered: 53 and time 2.406102000000004 seconds.
Data added for user number: 793 and numbered: 64 and time 4.4442550000000125 seconds.
Data added for user number: 302 and numbered: 39 and time 2.3108530000000087 seconds.
Data added for user number: 548 and numbered: 61 and time 2.94554500000001 seconds.
Data added for user number: 49 and numbered: 62 and time 2.922663 seconds.
Data added for user number: 794 and numbered: 59 and time 3.329818000000003 seconds.
Data added for user number: 303 and numbered: 43 and time 2.6440230000000042 seconds.

Data added for user number: 549 and numbered: 55 and time 2.153897999999998 seconds.
Data added for user number: 50 and numbered: 37 and time 1.1556769999999972 seconds.
Data added for user number: 795 and numbered: 41 and time 2.168975000000003 seconds.
Data added for user number: 51 and numbered: 60 and time 2.599893999999992 seconds.
Data added for user number: 550 and numbered: 63 and time 3.0116939999999914 seconds.
Data added for user number: 304 and numbered: 53 and time 3.6604950000000116 seconds.
Data added for user number: 796 and numbered: 47 and time 1.9466950000000054 seconds.
Data added for user number: 551 and numbered: 40 and time 1.438399000000004 seconds.
Data added for user number: 797 and numbered: 41 and time 1.8905429999999939 seconds.
Data added for user number: 52 and numbered: 61 and time 3.1284710000000047 seconds.
Data added for user number: 552 and numbered: 63 and time 2.664524 seconds.
Data added for user number: 53 and numbered: 51 and time 2.016020999999995 seconds.
Data added for user number: 798 and numbered: 59 and time 2.587857999999997 seconds.
Data added for user number: 305 and numbered: 64 and time 5.838934999999992 seconds.
Data added for user number: 553 and numbered: 52 and time 2.580204000000009 seconds.
Data added for user number: 799 and numbered: 41 and time 2.796420999999995 seconds.
Data added for user number: 54 and numbered: 61 and time 3.2380640000000085 seconds.
Data added for user number: 306 and numbered: 35 and time 2.0550290000000047 seconds.
Data added for user number: 554 and numbered: 58 and time 1.9355279999999908 seconds.
Data added for user number: 55 and numbered: 44 and time 2.219942000000003 seconds.
Data added for user number: 800 and numbered: 57 and time 2.636909000000003 seconds.
Data added for user number: 307 and numbered: 45 and time 2.5324309999999883 seconds.
Data added for user number: 555 and numbered: 55 and time 3.266588999999996 seconds.
Data added for user number: 56 and numbered: 44 and time 2.2559689999999932 seconds.
Data added for user number: 801 and numbered: 50 and time 2.2431820000000045 seconds.
Data added for user number: 556 and numbered: 50 and time 1.9796800000000019 seconds.
Data added for user number: 308 and numbered: 50 and time 3.215321000000003 seconds.
Data added for user number: 57 and numbered: 40 and time 3.1989360000000175 seconds.
Data added for user number: 309 and numbered: 63 and time 2.601454999999987 seconds.
Data added for user number: 557 and numbered: 56 and time 2.7509529999999813 seconds.
Data added for user number: 802 and numbered: 44 and time 3.769738999999987 seconds.
Data added for user number: 58 and numbered: 37 and time 1.8196020000000033 seconds.
Data added for user number: 310 and numbered: 48 and time 2.24531300000001 seconds.
Data added for user number: 803 and numbered: 38 and time 2.1989810000000034 seconds.
Data added for user number: 558 and numbered: 60 and time 3.361793000000006 seconds.
Data added for user number: 804 and numbered: 36 and time 1.4441630000000032 seconds.
Data added for user number: 59 and numbered: 64 and time 3.594516999999996 seconds.
Data added for user number: 311 and numbered: 54 and time 2.6718510000000038 seconds.
Data added for user number: 559 and numbered: 39 and time 2.8882370000000037 seconds.
Data added for user number: 60 and numbered: 37 and time 1.7211460000000045 seconds.
Data added for user number: 805 and numbered: 47 and time 2.7177610000000243 seconds.
Data added for user number: 312 and numbered: 44 and time 1.905922000000004 seconds.
Data added for user number: 313 and numbered: 42 and time 1.4831629999999905 seconds.
Data added for user number: 314 and numbered: 45 and time 1.4597750000000076 seconds.
Data added for user number: 560 and numbered: 62 and time 3.6303669999999784 seconds.
Data added for user number: 61 and numbered: 60 and time 4.030023999999997 seconds.
Data added for user number: 806 and numbered: 63 and time 4.916815000000014 seconds.
Data added for user number: 561 and numbered: 46 and time 2.253382000000016 seconds.
Data added for user number: 315 and numbered: 49 and time 2.53496100000001 seconds.
Data added for user number: 807 and numbered: 36 and time 2.1598649999999964 seconds.
Data added for user number: 62 and numbered: 51 and time 3.1506290000000092 seconds.
Data added for user number: 562 and numbered: 40 and time 1.8230640000000164 seconds.
Data added for user number: 808 and numbered: 52 and time 1.8446480000000065 seconds.
Data added for user number: 316 and numbered: 58 and time 4.28737799999999 seconds.
Data added for user number: 63 and numbered: 57 and time 3.789569 seconds.
Data added for user number: 563 and numbered: 62 and time 3.3885720000000106 seconds.
Data added for user number: 317 and numbered: 59 and time 2.6365869999999916 seconds.
Data added for user number: 809 and numbered: 64 and time 4.31189999999998 seconds.
Data added for user number: 64 and numbered: 50 and time 2.372070999999977 seconds.
Data added for user number: 564 and numbered: 61 and time 3.61445599999999 seconds.
Data added for user number: 65 and numbered: 41 and time 1.6412310000000048 seconds.
Data added for user number: 810 and numbered: 63 and time 2.9779620000000193 seconds.
Data added for user number: 565 and numbered: 53 and time 2.42655400000001 seconds.
Data added for user number: 318 and numbered: 60 and time 4.288283000000007 seconds.
Data added for user number: 66 and numbered: 43 and time 2.789321000000001 seconds.
Data added for user number: 319 and numbered: 38 and time 2.376542999999998 seconds.
Data added for user number: 67 and numbered: 48 and time 2.049547000000018 seconds.
Data added for user number: 566 and numbered: 52 and time 2.7891719999999793 seconds.
Data added for user number: 811 and numbered: 59 and time 5.523368000000005 seconds.
Data added for user number: 68 and numbered: 48 and time 2.2022269999999935 seconds.
Data added for user number: 812 and numbered: 36 and time 0.6979820000000245 seconds.
Data added for user number: 320 and numbered: 58 and time 3.1014399999999966 seconds.
Data added for user number: 567 and numbered: 44 and time 3.498142999999999 seconds.
Data added for user number: 321 and numbered: 62 and time 1.509190000000018 seconds.
Data added for user number: 813 and numbered: 50 and time 3.349158999999986 seconds.
Data added for user number: 568 and numbered: 52 and time 2.788509000000005 seconds.
Data added for user number: 322 and numbered: 52 and time 3.0258699999999976 seconds.
Data added for user number: 69 and numbered: 54 and time 6.543700999999999 seconds.
Data added for user number: 814 and numbered: 51 and time 3.176141000000001 seconds.
Data added for user number: 323 and numbered: 48 and time 2.192689999999999 seconds.
Data added for user number: 569 and numbered: 53 and time 3.2583700000000135 seconds.
Data added for user number: 70 and numbered: 50 and time 2.502892000000003 seconds.
Data added for user number: 71 and numbered: 48 and time 2.043697999999978 seconds.
Data added for user number: 570 and numbered: 57 and time 3.7468140000000005 seconds.
Data added for user number: 815 and numbered: 42 and time 4.171572999999995 seconds.
Data added for user number: 324 and numbered: 59 and time 4.280210000000011 seconds.
Data added for user number: 571 and numbered: 40 and time 1.5017100000000028 seconds.
Data added for user number: 325 and numbered: 41 and time 2.1716900000000123 seconds.
Data added for user number: 816 and numbered: 37 and time 3.5978509999999915 seconds.
Data added for user number: 572 and numbered: 52 and time 3.2884889999999984 seconds.
Data added for user number: 817 and numbered: 43 and time 1.4875079999999912 seconds.
Data added for user number: 326 and numbered: 53 and time 2.8532659999999908 seconds.
Data added for user number: 72 and numbered: 53 and time 5.910969999999992 seconds.
Data added for user number: 818 and numbered: 52 and time 1.9917250000000024 seconds.
Data added for user number: 327 and numbered: 50 and time 2.190320000000014 seconds.
Data added for user number: 573 and numbered: 49 and time 3.318731000000014 seconds.
Data added for user number: 73 and numbered: 44 and time 3.159492 seconds.

Data added for user number: 819 and numbered: 53 and time 2.58507800000001 seconds.
Data added for user number: 328 and numbered: 35 and time 2.154982999999987 seconds.
Data added for user number: 74 and numbered: 50 and time 1.3934089999999912 seconds.
Data added for user number: 820 and numbered: 50 and time 2.226270999999997 seconds.
Data added for user number: 574 and numbered: 43 and time 4.5040810000000135 seconds.
Data added for user number: 821 and numbered: 41 and time 1.3115960000000086 seconds.
Data added for user number: 75 and numbered: 63 and time 3.0522960000000126 seconds.
Data added for user number: 329 and numbered: 52 and time 4.938402999999994 seconds.
Data added for user number: 575 and numbered: 37 and time 2.821593000000007 seconds.
Data added for user number: 822 and numbered: 64 and time 2.448582999999985 seconds.
Data added for user number: 823 and numbered: 47 and time 0.8778630000000192 seconds.
Data added for user number: 76 and numbered: 51 and time 3.3587809999999934 seconds.
Data added for user number: 330 and numbered: 54 and time 3.3122710000000097 seconds.
Data added for user number: 576 and numbered: 37 and time 2.8936219999999935 seconds.
Data added for user number: 77 and numbered: 52 and time 2.67935700000001 seconds.
Data added for user number: 78 and numbered: 38 and time 1.458217000000019 seconds.
Data added for user number: 577 and numbered: 38 and time 2.818590999999998 seconds.
Data added for user number: 824 and numbered: 63 and time 4.69099700000001 seconds.
Data added for user number: 331 and numbered: 54 and time 4.262936999999994 seconds.
Data added for user number: 79 and numbered: 59 and time 2.720407000000023 seconds.
Data added for user number: 578 and numbered: 56 and time 2.911566999999991 seconds.
Data added for user number: 80 and numbered: 35 and time 1.5674140000000136 seconds.
Data added for user number: 825 and numbered: 50 and time 4.297550999999999 seconds.
Data added for user number: 332 and numbered: 60 and time 3.4587999999999965 seconds.
Data added for user number: 333 and numbered: 60 and time 1.6512189999999975 seconds.
Data added for user number: 579 and numbered: 64 and time 3.4643859999999904 seconds.
Data added for user number: 826 and numbered: 43 and time 3.333787000000001 seconds.
Data added for user number: 81 and numbered: 63 and time 4.158435999999995 seconds.
Data added for user number: 827 and numbered: 36 and time 1.1000959999999793 seconds.
Data added for user number: 580 and numbered: 64 and time 3.8667179999999917 seconds.
Data added for user number: 828 and numbered: 55 and time 2.1599660000000256 seconds.
Data added for user number: 334 and numbered: 53 and time 4.810422000000017 seconds.
Data added for user number: 82 and numbered: 59 and time 4.029270999999994 seconds.
Data added for user number: 581 and numbered: 58 and time 2.9296429999999987 seconds.
Data added for user number: 335 and numbered: 36 and time 2.488472999999999 seconds.
Data added for user number: 829 and numbered: 57 and time 3.202208000000013 seconds.
Data added for user number: 582 and numbered: 43 and time 2.1542860000000132 seconds.
Data added for user number: 830 and numbered: 50 and time 1.9405840000000012 seconds.
Data added for user number: 83 and numbered: 52 and time 4.022909999999996 seconds.
Data added for user number: 336 and numbered: 59 and time 3.2836949999999945 seconds.
Data added for user number: 831 and numbered: 36 and time 2.0143759999999986 seconds.
Data added for user number: 583 and numbered: 36 and time 3.0336340000000064 seconds.
Data added for user number: 84 and numbered: 56 and time 2.630129000000011 seconds.
Data added for user number: 337 and numbered: 36 and time 2.3793660000000045 seconds.
Data added for user number: 85 and numbered: 63 and time 2.4051660000000084 seconds.
Data added for user number: 584 and numbered: 57 and time 4.1195749999999975 seconds.
Data added for user number: 832 and numbered: 60 and time 4.4260209999999915 seconds.
Data added for user number: 585 and numbered: 44 and time 1.4770879999999806 seconds.
Data added for user number: 833 and numbered: 47 and time 1.9781289999999956 seconds.
Data added for user number: 338 and numbered: 62 and time 5.746100000000013 seconds.
Data added for user number: 586 and numbered: 35 and time 2.1291049999999814 seconds.
Data added for user number: 834 and numbered: 54 and time 2.467382999999984 seconds.
Data added for user number: 835 and numbered: 36 and time 1.089933000000002 seconds.
Data added for user number: 587 and numbered: 57 and time 2.094312000000002 seconds.
Data added for user number: 86 and numbered: 60 and time 6.9496249999999975 seconds.
Data added for user number: 836 and numbered: 37 and time 1.2492220000000032 seconds.
Data added for user number: 588 and numbered: 45 and time 2.6927589999999952 seconds.
Data added for user number: 339 and numbered: 42 and time 5.977006000000017 seconds.
Data added for user number: 87 and numbered: 55 and time 3.087311999999997 seconds.
Data added for user number: 837 and numbered: 63 and time 2.3416129999999953 seconds.
Data added for user number: 88 and numbered: 40 and time 1.585047000000003 seconds.
Data added for user number: 589 and numbered: 39 and time 3.378442000000007 seconds.
Data added for user number: 340 and numbered: 55 and time 3.5840889999999774 seconds.
Data added for user number: 838 and numbered: 62 and time 3.5407659999999908 seconds.
Data added for user number: 89 and numbered: 37 and time 2.746620000000007 seconds.
Data added for user number: 341 and numbered: 35 and time 2.7197470000000123 seconds.
Data added for user number: 590 and numbered: 45 and time 3.6036769999999763 seconds.
Data added for user number: 839 and numbered: 61 and time 3.6534340000000043 seconds.
Data added for user number: 591 and numbered: 40 and time 1.6167130000000043 seconds.
Data added for user number: 592 and numbered: 42 and time 1.1364680000000078 seconds.
Data added for user number: 90 and numbered: 61 and time 5.407483999999982 seconds.
Data added for user number: 342 and numbered: 44 and time 4.5098540000000185 seconds.
Data added for user number: 840 and numbered: 43 and time 3.8135350000000017 seconds.
Data added for user number: 343 and numbered: 38 and time 2.0494759999999985 seconds.
Data added for user number: 593 and numbered: 64 and time 3.363188000000008 seconds.
Data added for user number: 91 and numbered: 45 and time 3.1936369999999954 seconds.
Data added for user number: 344 and numbered: 57 and time 2.827928000000014 seconds.
Data added for user number: 841 and numbered: 64 and time 5.221720000000005 seconds.
Data added for user number: 92 and numbered: 63 and time 4.031839999999988 seconds.
Data added for user number: 594 and numbered: 56 and time 4.4918189999999925 seconds.
Data added for user number: 345 and numbered: 35 and time 2.3579030000000216 seconds.
Data added for user number: 842 and numbered: 44 and time 1.8483889999999974 seconds.
Data added for user number: 93 and numbered: 52 and time 3.7159340000000043 seconds.
Data added for user number: 595 and numbered: 60 and time 4.036694000000011 seconds.
Data added for user number: 346 and numbered: 58 and time 3.577764000000002 seconds.
Data added for user number: 843 and numbered: 63 and time 4.559585999999996 seconds.
Data added for user number: 596 and numbered: 44 and time 2.3401130000000023 seconds.
Data added for user number: 597 and numbered: 57 and time 1.5872300000000052 seconds.
Data added for user number: 347 and numbered: 41 and time 3.7933179999999993 seconds.
Data added for user number: 94 and numbered: 54 and time 4.638745999999998 seconds.
Data added for user number: 844 and numbered: 59 and time 3.914531000000011 seconds.
Data added for user number: 598 and numbered: 48 and time 2.1777680000000146 seconds.
Data added for user number: 348 and numbered: 37 and time 4.1179679999999905 seconds.
Data added for user number: 95 and numbered: 57 and time 3.9007819999999924 seconds.
Data added for user number: 599 and numbered: 61 and time 2.444790000000012 seconds.
Data added for user number: 96 and numbered: 43 and time 1.2980579999999975 seconds.
Data added for user number: 845 and numbered: 38 and time 3.938008999999994 seconds.

Data added for user number: 349 and numbered: 45 and time 2.7569819999999936 seconds.
Data added for user number: 600 and numbered: 44 and time 2.9263380000000154 seconds.
Data added for user number: 97 and numbered: 44 and time 2.7792449999999747 seconds.
Data added for user number: 350 and numbered: 44 and time 2.6771260000000154 seconds.
Data added for user number: 846 and numbered: 44 and time 3.946786000000003 seconds.
Data added for user number: 601 and numbered: 35 and time 3.16296600000004 seconds.
Data added for user number: 98 and numbered: 48 and time 2.7459249999999997 seconds.
Data added for user number: 602 and numbered: 56 and time 1.3100190000000111 seconds.
Data added for user number: 847 and numbered: 46 and time 3.250605999999948 seconds.
Data added for user number: 351 and numbered: 46 and time 3.4944380000000024 seconds.
Data added for user number: 99 and numbered: 54 and time 3.4224849999999947 seconds.
Data added for user number: 603 and numbered: 45 and time 4.16263600000002 seconds.
Data added for user number: 848 and numbered: 59 and time 3.4245710000000145 seconds.
Data added for user number: 604 and numbered: 49 and time 1.0625080000000366 seconds.
Data added for user number: 849 and numbered: 56 and time 2.837200999999993 seconds.
Data added for user number: 605 and numbered: 64 and time 2.1337520000000154 seconds.
Data added for user number: 352 and numbered: 62 and time 6.490456999999992 seconds.
Data added for user number: 100 and numbered: 43 and time 5.5565899999999715 seconds.
Data added for user number: 606 and numbered: 37 and time 2.4624330000000327 seconds.
Data added for user number: 850 and numbered: 47 and time 3.473727999999994 seconds.
Data added for user number: 353 and numbered: 37 and time 3.3973799999999983 seconds.
Data added for user number: 354 and numbered: 47 and time 1.973462999999981 seconds.
Data added for user number: 101 and numbered: 61 and time 5.292372 seconds.
Data added for user number: 607 and numbered: 40 and time 3.5539400000000114 seconds.
Data added for user number: 851 and numbered: 60 and time 2.6946189999999888 seconds.
Data added for user number: 355 and numbered: 62 and time 2.4375009999999975 seconds.
Data added for user number: 608 and numbered: 37 and time 2.918896000000018 seconds.
Data added for user number: 356 and numbered: 59 and time 1.6427489999999807 seconds.
Data added for user number: 102 and numbered: 35 and time 3.8942989999999895 seconds.
Data added for user number: 852 and numbered: 53 and time 5.350867999999991 seconds.
Data added for user number: 609 and numbered: 56 and time 3.4128789999999753 seconds.
Data added for user number: 357 and numbered: 61 and time 3.0516339999999786 seconds.
Data added for user number: 358 and numbered: 38 and time 1.4931990000000042 seconds.
Data added for user number: 103 and numbered: 54 and time 5.16185200000001 seconds.
Data added for user number: 853 and numbered: 48 and time 3.5507259999999974 seconds.
Data added for user number: 854 and numbered: 37 and time 1.9989030000000412 seconds.
Data added for user number: 104 and numbered: 49 and time 2.7154429999999934 seconds.
Data added for user number: 359 and numbered: 48 and time 3.5166340000000105 seconds.
Data added for user number: 610 and numbered: 50 and time 5.881677999999965 seconds.
Data added for user number: 105 and numbered: 40 and time 1.9106850000000009 seconds.
Data added for user number: 855 and numbered: 49 and time 2.634168000000045 seconds.
Data added for user number: 611 and numbered: 64 and time 2.780597 seconds.
Data added for user number: 856 and numbered: 40 and time 2.4823630000000207 seconds.
Data added for user number: 106 and numbered: 40 and time 2.6467380000000276 seconds.
Data added for user number: 360 and numbered: 39 and time 4.577225999999996 seconds.
Data added for user number: 612 and numbered: 56 and time 3.677645000000041 seconds.
Data added for user number: 107 and numbered: 42 and time 2.6593169999999873 seconds.
Data added for user number: 361 and numbered: 60 and time 4.457861999999977 seconds.
Data added for user number: 108 and numbered: 42 and time 2.1693329999999946 seconds.
Data added for user number: 857 and numbered: 60 and time 5.195013000000017 seconds.
Data added for user number: 613 and numbered: 38 and time 2.8408190000000104 seconds.
Data added for user number: 362 and numbered: 44 and time 2.8304789999999684 seconds.
Data added for user number: 858 and numbered: 50 and time 2.823547000000019 seconds.
Data added for user number: 614 and numbered: 48 and time 2.9954779999999914 seconds.
Data added for user number: 109 and numbered: 57 and time 4.521175000000028 seconds.
Data added for user number: 363 and numbered: 48 and time 2.6677030000000173 seconds.
Data added for user number: 364 and numbered: 43 and time 1.7386129999999866 seconds.
Data added for user number: 110 and numbered: 45 and time 3.0881459999999947 seconds.
Data added for user number: 615 and numbered: 57 and time 4.9749459999999885 seconds.
Data added for user number: 859 and numbered: 60 and time 5.604587999999978 seconds.
Data added for user number: 365 and numbered: 61 and time 3.4836310000000026 seconds.
Data added for user number: 366 and numbered: 51 and time 2.2746419999999716 seconds.
Data added for user number: 111 and numbered: 55 and time 5.568918999999994 seconds.
Data added for user number: 860 and numbered: 46 and time 4.911618999999973 seconds.
Data added for user number: 112 and numbered: 36 and time 2.0900479999999675 seconds.
Data added for user number: 367 and numbered: 44 and time 2.9403219999999806 seconds.
Data added for user number: 616 and numbered: 63 and time 7.447187000000042 seconds.
Data added for user number: 861 and numbered: 56 and time 3.4963169999999764 seconds.
Data added for user number: 862 and numbered: 46 and time 1.7353309999999738 seconds.
Data added for user number: 113 and numbered: 61 and time 3.984335999999985 seconds.
Data added for user number: 617 and numbered: 36 and time 3.7681329999999775 seconds.
Data added for user number: 114 and numbered: 57 and time 2.7239809999999807 seconds.
Data added for user number: 863 and numbered: 42 and time 4.812987999999962 seconds.
Data added for user number: 368 and numbered: 50 and time 8.316587000000027 seconds.
Data added for user number: 115 and numbered: 59 and time 2.111706999999967 seconds.
Data added for user number: 618 and numbered: 40 and time 4.681078000000014 seconds.
Data added for user number: 864 and numbered: 48 and time 2.9210559999999646 seconds.
Data added for user number: 116 and numbered: 40 and time 2.566032000000007 seconds.
Data added for user number: 865 and numbered: 35 and time 1.6423749999999586 seconds.
Data added for user number: 369 and numbered: 56 and time 4.864004000000023 seconds.
Data added for user number: 117 and numbered: 62 and time 4.445785999999998 seconds.
Data added for user number: 619 and numbered: 57 and time 6.770177999999987 seconds.
Data added for user number: 866 and numbered: 47 and time 3.499018000000035 seconds.
Data added for user number: 620 and numbered: 61 and time 2.773787000000027 seconds.
Data added for user number: 370 and numbered: 61 and time 5.795488999999975 seconds.
Data added for user number: 867 and numbered: 57 and time 3.143652999999972 seconds.
Data added for user number: 621 and numbered: 35 and time 2.3351279999999974 seconds.
Data added for user number: 371 and numbered: 57 and time 2.930273999999997 seconds.
Data added for user number: 118 and numbered: 46 and time 7.235658999999998 seconds.
Data added for user number: 868 and numbered: 40 and time 4.282276000000024 seconds.
Data added for user number: 622 and numbered: 56 and time 3.1363699999999994 seconds.
Data added for user number: 372 and numbered: 51 and time 4.79329899999999 seconds.
Data added for user number: 119 and numbered: 60 and time 4.583065000000033 seconds.
Data added for user number: 869 and numbered: 57 and time 4.950006999999971 seconds.
Data added for user number: 623 and numbered: 61 and time 5.646743000000015 seconds.
Data added for user number: 120 and numbered: 54 and time 3.7411050000000046 seconds.
Data added for user number: 373 and numbered: 46 and time 5.163326999999981 seconds.

Data added for user number: 624 and numbered: 51 and time 2.670735000000036 seconds.
Data added for user number: 870 and numbered: 48 and time 5.535984999999982 seconds.
Data added for user number: 121 and numbered: 64 and time 4.385123000000021 seconds.
Data added for user number: 625 and numbered: 39 and time 4.100774000000001 seconds.
Data added for user number: 374 and numbered: 48 and time 4.614120000000014 seconds.
Data added for user number: 626 and numbered: 36 and time 1.6625909999999635 seconds.
Data added for user number: 871 and numbered: 51 and time 4.659689999999955 seconds.
Data added for user number: 122 and numbered: 60 and time 4.970945000000029 seconds.
Data added for user number: 627 and numbered: 37 and time 2.8492160000000126 seconds.
Data added for user number: 375 and numbered: 44 and time 4.400931000000014 seconds.
Data added for user number: 872 and numbered: 56 and time 2.51432699999998 seconds.
Data added for user number: 376 and numbered: 37 and time 2.295233000000053 seconds.
Data added for user number: 123 and numbered: 37 and time 3.174203000000034 seconds.
Data added for user number: 873 and numbered: 55 and time 4.245429999999999 seconds.
Data added for user number: 628 and numbered: 59 and time 5.26307300000002 seconds.
Data added for user number: 377 and numbered: 44 and time 4.1637699999999995 seconds.
Data added for user number: 124 and numbered: 42 and time 4.876486999999997 seconds.
Data added for user number: 874 and numbered: 45 and time 3.9029500000000326 seconds.
Data added for user number: 629 and numbered: 53 and time 4.187023000000011 seconds.
Data added for user number: 125 and numbered: 41 and time 2.578634999999963 seconds.
Data added for user number: 378 and numbered: 63 and time 4.7868969999999536 seconds.
Data added for user number: 630 and numbered: 37 and time 2.769841999999983 seconds.
Data added for user number: 126 and numbered: 50 and time 2.547877999999969 seconds.
Data added for user number: 875 and numbered: 59 and time 4.537260000000003 seconds.
Data added for user number: 631 and numbered: 35 and time 2.8978399999999738 seconds.
Data added for user number: 379 and numbered: 35 and time 4.2001280000000065 seconds.
Data added for user number: 876 and numbered: 36 and time 3.5888779999999656 seconds.
Data added for user number: 127 and numbered: 56 and time 4.6321700000000305 seconds.
Data added for user number: 632 and numbered: 36 and time 2.5071609999999964 seconds.
Data added for user number: 380 and numbered: 39 and time 2.2757740000000126 seconds.
Data added for user number: 128 and numbered: 36 and time 1.7508209999999735 seconds.
Data added for user number: 877 and numbered: 51 and time 3.341344000000049 seconds.
Data added for user number: 633 and numbered: 47 and time 3.931508000000008 seconds.
Data added for user number: 381 and numbered: 53 and time 4.777479999999969 seconds.
Data added for user number: 878 and numbered: 42 and time 4.006392000000005 seconds.
Data added for user number: 129 and numbered: 60 and time 6.772465000000011 seconds.
Data added for user number: 634 and numbered: 62 and time 4.740710999999976 seconds.
Data added for user number: 879 and numbered: 55 and time 3.830709000000013 seconds.
Data added for user number: 382 and numbered: 49 and time 5.578624999999988 seconds.
Data added for user number: 130 and numbered: 52 and time 2.641202000000021 seconds.
Data added for user number: 635 and numbered: 43 and time 3.396551000000045 seconds.
Data added for user number: 383 and numbered: 56 and time 4.057246000000021 seconds.
Data added for user number: 131 and numbered: 57 and time 4.533918999999969 seconds.
Data added for user number: 880 and numbered: 54 and time 5.324380000000019 seconds.
Data added for user number: 132 and numbered: 50 and time 1.6933280000000082 seconds.
Data added for user number: 636 and numbered: 60 and time 5.82460100000003 seconds.
Data added for user number: 133 and numbered: 47 and time 3.2075419999999895 seconds.
Data added for user number: 384 and numbered: 49 and time 6.524094999999988 seconds.
Data added for user number: 881 and numbered: 53 and time 5.681693999999993 seconds.
Data added for user number: 637 and numbered: 63 and time 5.590626999999984 seconds.
Data added for user number: 385 and numbered: 39 and time 2.656296999999995 seconds.
Data added for user number: 134 and numbered: 52 and time 3.8632800000000316 seconds.
Data added for user number: 882 and numbered: 54 and time 4.461786000000018 seconds.
Data added for user number: 883 and numbered: 39 and time 2.1607500000000073 seconds.
Data added for user number: 638 and numbered: 52 and time 4.978703000000053 seconds.
Data added for user number: 386 and numbered: 46 and time 4.752466999999967 seconds.
Data added for user number: 135 and numbered: 50 and time 5.879980999999987 seconds.
Data added for user number: 387 and numbered: 54 and time 4.410611000000017 seconds.
Data added for user number: 884 and numbered: 58 and time 5.833849999999984 seconds.
Data added for user number: 639 and numbered: 62 and time 5.41882499999997 seconds.
Data added for user number: 136 and numbered: 59 and time 6.494700999999964 seconds.
Data added for user number: 388 and numbered: 62 and time 4.400672000000043 seconds.
Data added for user number: 640 and numbered: 35 and time 4.347403999999983 seconds.
Data added for user number: 885 and numbered: 61 and time 5.922999000000004 seconds.
Data added for user number: 389 and numbered: 58 and time 3.3462010000000078 seconds.
Data added for user number: 137 and numbered: 50 and time 4.356376000000012 seconds.
Data added for user number: 641 and numbered: 43 and time 3.182926000000009 seconds.
Data added for user number: 642 and numbered: 45 and time 2.7861149999999952 seconds.
Data added for user number: 886 and numbered: 60 and time 5.533798999999988 seconds.
Data added for user number: 138 and numbered: 57 and time 4.525976000000014 seconds.
Data added for user number: 390 and numbered: 39 and time 6.350234999999998 seconds.
Data added for user number: 139 and numbered: 36 and time 2.758084999999994 seconds.
Data added for user number: 887 and numbered: 46 and time 3.258053000000018 seconds.
Data added for user number: 643 and numbered: 53 and time 5.229851999999994 seconds.
Data added for user number: 391 and numbered: 37 and time 3.4479990000000384 seconds.
Data added for user number: 888 and numbered: 38 and time 2.4753049999999917 seconds.
Data added for user number: 644 and numbered: 47 and time 3.7117769999999837 seconds.
Data added for user number: 392 and numbered: 40 and time 3.4129839999999945 seconds.
Data added for user number: 140 and numbered: 64 and time 6.428695000000005 seconds.
Data added for user number: 645 and numbered: 40 and time 2.7908180000000016 seconds.
Data added for user number: 889 and numbered: 52 and time 5.507356999999956 seconds.
Data added for user number: 141 and numbered: 35 and time 2.7620790000000284 seconds.
Data added for user number: 393 and numbered: 45 and time 4.550566000000003 seconds.
Data added for user number: 890 and numbered: 36 and time 3.497043000000019 seconds.
Data added for user number: 394 and numbered: 42 and time 2.3415540000000306 seconds.
Data added for user number: 646 and numbered: 61 and time 5.443090999999981 seconds.
Data added for user number: 142 and numbered: 48 and time 4.218582999999967 seconds.
Data added for user number: 891 and numbered: 44 and time 3.0382079999999974 seconds.
Data added for user number: 395 and numbered: 40 and time 4.293331000000023 seconds.
Data added for user number: 143 and numbered: 49 and time 3.687306000000035 seconds.
Data added for user number: 647 and numbered: 36 and time 4.565188999999975 seconds.
Data added for user number: 648 and numbered: 36 and time 2.2228470000000016 seconds.
Data added for user number: 396 and numbered: 46 and time 3.432434999999998 seconds.
Data added for user number: 892 and numbered: 60 and time 5.975790999999958 seconds.
Data added for user number: 144 and numbered: 60 and time 4.392210000000034 seconds.
Data added for user number: 893 and numbered: 54 and time 3.7455360000000155 seconds.
Data added for user number: 145 and numbered: 50 and time 3.0992749999999774 seconds.

Data added for user number: 649 and numbered: 39 and time 5.289242999999999 seconds.
Data added for user number: 397 and numbered: 62 and time 5.920911999999987 seconds.
Data added for user number: 894 and numbered: 36 and time 2.5832679999999755 seconds.
Data added for user number: 146 and numbered: 42 and time 3.9779480000000262 seconds.
Data added for user number: 650 and numbered: 37 and time 3.6035989999999742 seconds.
Data added for user number: 398 and numbered: 37 and time 4.251764999999978 seconds.
Data added for user number: 895 and numbered: 51 and time 4.0011670000000095 seconds.
Data added for user number: 147 and numbered: 45 and time 3.0323489999999538 seconds.
Data added for user number: 896 and numbered: 54 and time 3.459705999999983 seconds.
Data added for user number: 399 and numbered: 46 and time 4.116714000000002 seconds.
Data added for user number: 651 and numbered: 60 and time 6.587873000000002 seconds.
Data added for user number: 148 and numbered: 42 and time 5.249271999999962 seconds.
Data added for user number: 897 and numbered: 51 and time 4.372393999999986 seconds.
Data added for user number: 149 and numbered: 45 and time 2.9032490000000166 seconds.
Data added for user number: 652 and numbered: 59 and time 6.179087999999979 seconds.
Data added for user number: 400 and numbered: 57 and time 7.6708340000000135 seconds.
Data added for user number: 898 and numbered: 44 and time 5.24272000000002 seconds.
Data added for user number: 401 and numbered: 41 and time 3.12017400000002 seconds.
Data added for user number: 150 and numbered: 64 and time 5.6164360000000215 seconds.
Data added for user number: 653 and numbered: 57 and time 4.276221000000021 seconds.
Data added for user number: 151 and numbered: 58 and time 2.8035240000000385 seconds.
Data added for user number: 899 and numbered: 40 and time 5.482874999999979 seconds.
Data added for user number: 402 and numbered: 54 and time 4.802680000000009 seconds.
Data added for user number: 152 and numbered: 57 and time 4.403977999999995 seconds.
Data added for user number: 900 and numbered: 37 and time 3.2022040000000516 seconds.
Data added for user number: 654 and numbered: 42 and time 7.227411000000018 seconds.
Data added for user number: 655 and numbered: 35 and time 2.749629999999968 seconds.
Data added for user number: 403 and numbered: 63 and time 5.758696999999984 seconds.
Data added for user number: 901 and numbered: 59 and time 4.686379000000045 seconds.
Data added for user number: 153 and numbered: 49 and time 5.198621000000003 seconds.
Data added for user number: 404 and numbered: 35 and time 2.7934529999999995 seconds.
Data added for user number: 405 and numbered: 46 and time 3.051625999999999 seconds.
Data added for user number: 902 and numbered: 56 and time 5.422651999999971 seconds.
Data added for user number: 656 and numbered: 46 and time 7.2628010000000245 seconds.
Data added for user number: 154 and numbered: 60 and time 5.708627999999976 seconds.
Data added for user number: 406 and numbered: 48 and time 3.2461659999999597 seconds.
Data added for user number: 903 and numbered: 44 and time 3.9488910000000033 seconds.
Data added for user number: 657 and numbered: 62 and time 4.611431999999979 seconds.
Data added for user number: 407 and numbered: 50 and time 3.1572889999999916 seconds.
Data added for user number: 155 and numbered: 40 and time 5.397327000000018 seconds.
Data added for user number: 904 and numbered: 35 and time 3.1166170000000193 seconds.
Data added for user number: 658 and numbered: 45 and time 2.815990999999997 seconds.
Data added for user number: 905 and numbered: 48 and time 2.522841000000028 seconds.
Data added for user number: 156 and numbered: 50 and time 4.55915200000004 seconds.
Data added for user number: 408 and numbered: 57 and time 5.596650999999952 seconds.
Data added for user number: 906 and numbered: 48 and time 4.260620000000017 seconds.
Data added for user number: 409 and numbered: 40 and time 3.491061000000002 seconds.
Data added for user number: 659 and numbered: 48 and time 7.078678000000025 seconds.
Data added for user number: 157 and numbered: 50 and time 4.350781999999981 seconds.
Data added for user number: 907 and numbered: 46 and time 3.072232999999983 seconds.
Data added for user number: 660 and numbered: 35 and time 3.8609260000000063 seconds.
Data added for user number: 158 and numbered: 64 and time 5.109509000000003 seconds.
Data added for user number: 410 and numbered: 54 and time 5.833696999999972 seconds.
Data added for user number: 908 and numbered: 48 and time 4.637006999999983 seconds.
Data added for user number: 411 and numbered: 35 and time 3.0785600000000386 seconds.
Data added for user number: 661 and numbered: 56 and time 5.455890999999951 seconds.
Data added for user number: 412 and numbered: 36 and time 3.3968430000000467 seconds.
Data added for user number: 909 and numbered: 59 and time 6.367330000000038 seconds.
Data added for user number: 662 and numbered: 46 and time 3.9739790000000426 seconds.
Data added for user number: 159 and numbered: 63 and time 8.453751000000011 seconds.
Data added for user number: 160 and numbered: 36 and time 2.511905000000013 seconds.
Data added for user number: 910 and numbered: 56 and time 3.851945999999998 seconds.
Data added for user number: 413 and numbered: 55 and time 5.51428599999997 seconds.
Data added for user number: 663 and numbered: 55 and time 5.536540000000002 seconds.
Data added for user number: 161 and numbered: 46 and time 2.939624999999978 seconds.
Data added for user number: 911 and numbered: 55 and time 5.723275000000001 seconds.
Data added for user number: 664 and numbered: 58 and time 4.303493000000003 seconds.
Data added for user number: 414 and numbered: 56 and time 7.161827000000017 seconds.
Data added for user number: 162 and numbered: 58 and time 6.122491000000082 seconds.
Data added for user number: 665 and numbered: 45 and time 3.646331000000032 seconds.
Data added for user number: 912 and numbered: 50 and time 6.530889000000002 seconds.
Data added for user number: 163 and numbered: 62 and time 5.110779999999977 seconds.
Data added for user number: 666 and numbered: 38 and time 3.8380109999999377 seconds.
Data added for user number: 415 and numbered: 63 and time 6.875419000000079 seconds.
Data added for user number: 913 and numbered: 45 and time 4.188551000000075 seconds.
Data added for user number: 416 and numbered: 37 and time 2.918042000000014 seconds.
Data added for user number: 164 and numbered: 53 and time 6.917141999999899 seconds.
Data added for user number: 667 and numbered: 61 and time 7.097811999999976 seconds.
Data added for user number: 914 and numbered: 60 and time 5.13882000000001 seconds.
Data added for user number: 668 and numbered: 47 and time 2.1314820000000054 seconds.
Data added for user number: 417 and numbered: 47 and time 6.053342000000043 seconds.
Data added for user number: 915 and numbered: 41 and time 3.506953000000067 seconds.
Data added for user number: 165 and numbered: 54 and time 6.524207000000047 seconds.
Data added for user number: 669 and numbered: 50 and time 4.487405000000081 seconds.
Data added for user number: 916 and numbered: 38 and time 3.3387179999999717 seconds.
Data added for user number: 418 and numbered: 61 and time 6.295397999999977 seconds.
Data added for user number: 917 and numbered: 60 and time 2.971208000000047 seconds.
Data added for user number: 670 and numbered: 53 and time 6.1433660000000145 seconds.
Data added for user number: 918 and numbered: 50 and time 2.9734280000000126 seconds.
Data added for user number: 419 and numbered: 49 and time 6.480330999999978 seconds.
Data added for user number: 166 and numbered: 57 and time 9.648402000000033 seconds.
Data added for user number: 671 and numbered: 42 and time 3.4097419999999374 seconds.
Data added for user number: 919 and numbered: 40 and time 3.7439259999999877 seconds.
Data added for user number: 167 and numbered: 36 and time 3.4154060000000754 seconds.
Data added for user number: 672 and numbered: 56 and time 3.1722540000000663 seconds.
Data added for user number: 420 and numbered: 52 and time 4.596442000000025 seconds.
Data added for user number: 421 and numbered: 62 and time 3.7506740000000036 seconds.

Data added for user number: 673 and numbered: 41 and time 5.2624139999999215 seconds.
Data added for user number: 920 and numbered: 55 and time 8.018838000000073 seconds.
Data added for user number: 422 and numbered: 51 and time 3.1253300000000763 seconds.
Data added for user number: 168 and numbered: 64 and time 8.289025999999922 seconds.
Data added for user number: 921 and numbered: 39 and time 3.5333080000000336 seconds.
Data added for user number: 423 and numbered: 58 and time 3.994440000000054 seconds.
Data added for user number: 922 and numbered: 47 and time 3.6674299999999675 seconds.
Data added for user number: 169 and numbered: 60 and time 5.608581999999956 seconds.
Data added for user number: 674 and numbered: 56 and time 8.71119299999998 seconds.
Data added for user number: 923 and numbered: 48 and time 3.895271999999977 seconds.
Data added for user number: 675 and numbered: 49 and time 3.703475000000026 seconds.
Data added for user number: 170 and numbered: 47 and time 4.516896999999972 seconds.
Data added for user number: 676 and numbered: 44 and time 1.6252210000000105 seconds.
Data added for user number: 424 and numbered: 64 and time 7.790907999999945 seconds.
Data added for user number: 924 and numbered: 51 and time 6.721325999999976 seconds.
Data added for user number: 677 and numbered: 57 and time 4.719371000000024 seconds.
Data added for user number: 425 and numbered: 59 and time 5.952672000000007 seconds.
Data added for user number: 426 and numbered: 35 and time 2.1907560000000785 seconds.
Data added for user number: 171 and numbered: 52 and time 9.459490999999957 seconds.
Data added for user number: 678 and numbered: 36 and time 4.291896999999949 seconds.
Data added for user number: 925 and numbered: 59 and time 5.055947999999944 seconds.
Data added for user number: 172 and numbered: 55 and time 4.10480599999994 seconds.
Data added for user number: 427 and numbered: 49 and time 6.9748670000000175 seconds.
Data added for user number: 679 and numbered: 58 and time 6.400585999999976 seconds.
Data added for user number: 926 and numbered: 57 and time 5.9743009999999686 seconds.
Data added for user number: 173 and numbered: 39 and time 4.485220000000027 seconds.
Data added for user number: 428 and numbered: 36 and time 4.951340000000073 seconds.
Data added for user number: 927 and numbered: 56 and time 4.763615999999956 seconds.
Data added for user number: 680 and numbered: 47 and time 5.661578999999961 seconds.
Data added for user number: 174 and numbered: 60 and time 5.052767999999901 seconds.
Data added for user number: 928 and numbered: 53 and time 4.223940999999968 seconds.
Data added for user number: 175 and numbered: 44 and time 4.575261000000069 seconds.
Data added for user number: 429 and numbered: 62 and time 6.587247000000048 seconds.
Data added for user number: 681 and numbered: 51 and time 6.029886000000033 seconds.
Data added for user number: 929 and numbered: 35 and time 3.3624320000000125 seconds.
Data added for user number: 430 and numbered: 37 and time 3.3166700000000446 seconds.
Data added for user number: 176 and numbered: 48 and time 5.344299999999976 seconds.
Data added for user number: 431 and numbered: 37 and time 2.246766999999977 seconds.
Data added for user number: 930 and numbered: 49 and time 6.078394000000003 seconds.
Data added for user number: 177 and numbered: 38 and time 2.2253900000000613 seconds.
Data added for user number: 432 and numbered: 36 and time 2.2365780000000086 seconds.
Data added for user number: 682 and numbered: 48 and time 7.980662999999936 seconds.
Data added for user number: 931 and numbered: 38 and time 3.8086530000000494 seconds.
Data added for user number: 683 and numbered: 46 and time 4.296449999999936 seconds.
Data added for user number: 178 and numbered: 58 and time 5.439101999999934 seconds.
Data added for user number: 433 and numbered: 63 and time 6.441262000000052 seconds.
Data added for user number: 179 and numbered: 35 and time 2.489824999999996 seconds.
Data added for user number: 932 and numbered: 38 and time 6.192056000000093 seconds.
Data added for user number: 434 and numbered: 53 and time 3.652643000000012 seconds.
Data added for user number: 684 and numbered: 54 and time 7.325924999999984 seconds.
Data added for user number: 180 and numbered: 55 and time 4.852527000000009 seconds.
Data added for user number: 435 and numbered: 47 and time 4.6914350000000695 seconds.
Data added for user number: 436 and numbered: 38 and time 1.554877999999917 seconds.
Data added for user number: 933 and numbered: 57 and time 6.969785000000002 seconds.
Data added for user number: 181 and numbered: 60 and time 4.874098000000004 seconds.
Data added for user number: 685 and numbered: 35 and time 6.001003999999966 seconds.
Data added for user number: 437 and numbered: 50 and time 4.5879209999999375 seconds.
Data added for user number: 182 and numbered: 49 and time 3.80642899999998 seconds.
Data added for user number: 686 and numbered: 58 and time 6.354712999999947 seconds.
Data added for user number: 438 and numbered: 59 and time 3.5045160000000806 seconds.
Data added for user number: 934 and numbered: 57 and time 8.602660000000014 seconds.
Data added for user number: 183 and numbered: 48 and time 7.006884000000014 seconds.
Data added for user number: 439 and numbered: 47 and time 4.277868000000012 seconds.
Data added for user number: 687 and numbered: 52 and time 5.160140999999953 seconds.
Data added for user number: 935 and numbered: 58 and time 5.019401000000016 seconds.
Data added for user number: 440 and numbered: 54 and time 5.939652000000024 seconds.
Data added for user number: 184 and numbered: 57 and time 6.987860999999953 seconds.
Data added for user number: 688 and numbered: 61 and time 5.744423999999981 seconds.
Data added for user number: 936 and numbered: 37 and time 6.300429000000008 seconds.
Data added for user number: 937 and numbered: 48 and time 2.8793550000000323 seconds.
Data added for user number: 441 and numbered: 57 and time 5.365467999999964 seconds.
Data added for user number: 185 and numbered: 50 and time 7.329486000000088 seconds.
Data added for user number: 938 and numbered: 43 and time 3.681479000000081 seconds.
Data added for user number: 689 and numbered: 62 and time 8.518021999999974 seconds.
Data added for user number: 186 and numbered: 42 and time 5.7103799999999865 seconds.
Data added for user number: 939 and numbered: 46 and time 5.6465010000000575 seconds.
Data added for user number: 442 and numbered: 57 and time 10.055574000000092 seconds.
Data added for user number: 690 and numbered: 64 and time 7.503991000000042 seconds.
Data added for user number: 940 and numbered: 42 and time 4.112965999999915 seconds.
Data added for user number: 443 and numbered: 44 and time 4.495969999999943 seconds.
Data added for user number: 187 and numbered: 47 and time 6.811100999999894 seconds.
Data added for user number: 691 and numbered: 59 and time 6.111964000000057 seconds.
Data added for user number: 941 and numbered: 57 and time 6.33176299999991 seconds.
Data added for user number: 188 and numbered: 41 and time 5.0080749999999625 seconds.
Data added for user number: 444 and numbered: 58 and time 5.800544999999943 seconds.
Data added for user number: 692 and numbered: 40 and time 5.439576999999986 seconds.
Data added for user number: 445 and numbered: 50 and time 4.656579999999963 seconds.
Data added for user number: 942 and numbered: 49 and time 6.463862999999947 seconds.
Data added for user number: 189 and numbered: 64 and time 6.460129000000052 seconds.
Data added for user number: 693 and numbered: 36 and time 3.6648739999999407 seconds.
Data added for user number: 446 and numbered: 36 and time 3.6825830000000224 seconds.
Data added for user number: 943 and numbered: 42 and time 4.806562999999983 seconds.
Data added for user number: 190 and numbered: 39 and time 4.667989000000034 seconds.
Data added for user number: 694 and numbered: 47 and time 6.892885999999976 seconds.
Data added for user number: 447 and numbered: 41 and time 5.604207999999971 seconds.
Data added for user number: 695 and numbered: 36 and time 1.969047000000046 seconds.
Data added for user number: 191 and numbered: 40 and time 4.862621999999988 seconds.

Data added for user number: 944 and numbered: 53 and time 7.489930999999956 seconds.
Data added for user number: 192 and numbered: 61 and time 4.595493999999917 seconds.
Data added for user number: 696 and numbered: 53 and time 5.868536999999947 seconds.
Data added for user number: 945 and numbered: 47 and time 4.493436999999972 seconds.
Data added for user number: 193 and numbered: 44 and time 3.37127600000008 seconds.
Data added for user number: 448 and numbered: 64 and time 10.182718000000023 seconds.
Data added for user number: 449 and numbered: 50 and time 4.037350999999944 seconds.
Data added for user number: 697 and numbered: 63 and time 8.506542999999965 seconds.
Data added for user number: 946 and numbered: 56 and time 7.512921000000006 seconds.
Data added for user number: 194 and numbered: 54 and time 7.939468999999917 seconds.
Data added for user number: 450 and numbered: 41 and time 4.548995999999988 seconds.
Data added for user number: 947 and numbered: 45 and time 4.315021999999999 seconds.
Data added for user number: 698 and numbered: 51 and time 5.0367650000000594 seconds.
Data added for user number: 195 and numbered: 47 and time 2.982974000000013 seconds.
Data added for user number: 451 and numbered: 43 and time 4.71723499999996 seconds.
Data added for user number: 699 and numbered: 39 and time 4.186688000000004 seconds.
Data added for user number: 196 and numbered: 41 and time 4.429516000000035 seconds.
Data added for user number: 948 and numbered: 63 and time 6.155889000000002 seconds.
Data added for user number: 452 and numbered: 60 and time 7.134933000000046 seconds.
Data added for user number: 197 and numbered: 57 and time 5.6970870000000104 seconds.
Data added for user number: 700 and numbered: 64 and time 6.155938999999989 seconds.
Data added for user number: 949 and numbered: 50 and time 8.305275000000051 seconds.
Data added for user number: 701 and numbered: 35 and time 5.166747999999984 seconds.
Data added for user number: 198 and numbered: 48 and time 5.873787000000107 seconds.
Data added for user number: 453 and numbered: 53 and time 6.457468999999946 seconds.
Data added for user number: 950 and numbered: 36 and time 4.465829999999983 seconds.
Data added for user number: 702 and numbered: 35 and time 3.599725000000035 seconds.
Data added for user number: 951 and numbered: 37 and time 4.012174000000073 seconds.
Data added for user number: 454 and numbered: 48 and time 5.6650789999999915 seconds.
Data added for user number: 199 and numbered: 61 and time 8.107279999999946 seconds.
Data added for user number: 703 and numbered: 53 and time 6.074131999999963 seconds.
Data added for user number: 455 and numbered: 41 and time 2.991059000000064 seconds.
Data added for user number: 952 and numbered: 57 and time 5.656651000000011 seconds.
Data added for user number: 704 and numbered: 57 and time 4.7050440000000435 seconds.
Data added for user number: 456 and numbered: 38 and time 4.852070000000026 seconds.
Data added for user number: 705 and numbered: 47 and time 2.765337000000045 seconds.
Data added for user number: 457 and numbered: 48 and time 3.1816880000000083 seconds.
Data added for user number: 200 and numbered: 60 and time 10.672093000000018 seconds.
Data added for user number: 953 and numbered: 36 and time 7.330608999999981 seconds.
Data added for user number: 458 and numbered: 57 and time 5.041762999999946 seconds.
Data added for user number: 706 and numbered: 60 and time 6.56670100000008 seconds.
Data added for user number: 954 and numbered: 60 and time 6.752990999999952 seconds.
Data added for user number: 201 and numbered: 61 and time 8.839737000000014 seconds.
Data added for user number: 459 and numbered: 45 and time 5.511633999999958 seconds.
Data added for user number: 707 and numbered: 42 and time 5.804536999999982 seconds.
Data added for user number: 460 and numbered: 45 and time 4.28101700000002 seconds.
Data added for user number: 955 and numbered: 49 and time 6.647230000000036 seconds.
Data added for user number: 202 and numbered: 44 and time 5.852402999999981 seconds.
Data added for user number: 708 and numbered: 45 and time 4.757469000000015 seconds.
Data added for user number: 461 and numbered: 41 and time 4.829963000000021 seconds.
Data added for user number: 709 and numbered: 53 and time 5.20326 seconds.
Data added for user number: 956 and numbered: 60 and time 7.0518749999999955 seconds.
Data added for user number: 203 and numbered: 64 and time 7.524663000000032 seconds.
Data added for user number: 462 and numbered: 39 and time 5.044212000000016 seconds.
Data added for user number: 957 and numbered: 36 and time 2.728572999999983 seconds.
Data added for user number: 710 and numbered: 44 and time 6.340565999999967 seconds.
Data added for user number: 958 and numbered: 61 and time 4.145501999999965 seconds.
Data added for user number: 463 and numbered: 43 and time 6.687455 seconds.
Data added for user number: 204 and numbered: 51 and time 8.090260999999941 seconds.
Data added for user number: 959 and numbered: 43 and time 4.229524999999967 seconds.
Data added for user number: 711 and numbered: 56 and time 5.677343000000064 seconds.
Data added for user number: 464 and numbered: 48 and time 5.422867999999994 seconds.
Data added for user number: 960 and numbered: 44 and time 4.150513000000046 seconds.
Data added for user number: 205 and numbered: 55 and time 7.382185999999933 seconds.
Data added for user number: 961 and numbered: 45 and time 3.30957699999999 seconds.
Data added for user number: 712 and numbered: 61 and time 8.412738999999988 seconds.
Data added for user number: 465 and numbered: 43 and time 7.114262999999937 seconds.
Data added for user number: 206 and numbered: 43 and time 6.085134000000039 seconds.
Data added for user number: 713 and numbered: 62 and time 3.7719149999999217 seconds.
Data added for user number: 962 and numbered: 64 and time 8.40430200000003 seconds.
Data added for user number: 466 and numbered: 62 and time 6.444792000000007 seconds.
Data added for user number: 714 and numbered: 53 and time 4.962671 seconds.
Data added for user number: 715 and numbered: 63 and time 2.8250620000000026 seconds.
Data added for user number: 207 and numbered: 59 and time 9.999974000000066 seconds.
Data added for user number: 208 and numbered: 37 and time 2.781649000000016 seconds.
Data added for user number: 963 and numbered: 54 and time 8.965929999999958 seconds.
Data added for user number: 716 and numbered: 57 and time 4.75925200000006 seconds.
Data added for user number: 467 and numbered: 47 and time 8.950546000000031 seconds.
Data added for user number: 468 and numbered: 38 and time 2.0138660000000073 seconds.
Data added for user number: 717 and numbered: 37 and time 3.2988789999999426 seconds.
Data added for user number: 718 and numbered: 54 and time 1.791749999999979 seconds.
Data added for user number: 209 and numbered: 53 and time 6.1518729999999096 seconds.
Data added for user number: 469 and numbered: 39 and time 4.342690999999945 seconds.
Data added for user number: 210 and numbered: 58 and time 3.6259919999999966 seconds.
Data added for user number: 964 and numbered: 40 and time 10.262655999999993 seconds.
Data added for user number: 719 and numbered: 48 and time 5.655093000000079 seconds.
Data added for user number: 470 and numbered: 47 and time 5.527259999999956 seconds.
Data added for user number: 965 and numbered: 36 and time 3.031176000000073 seconds.
Data added for user number: 211 and numbered: 55 and time 4.935998999999924 seconds.
Data added for user number: 212 and numbered: 43 and time 2.637456000000043 seconds.
Data added for user number: 720 and numbered: 58 and time 7.140693000000056 seconds.
Data added for user number: 213 and numbered: 41 and time 3.888106999999991 seconds.
Data added for user number: 471 and numbered: 51 and time 8.175822999999923 seconds.
Data added for user number: 966 and numbered: 62 and time 8.305893000000083 seconds.
Data added for user number: 472 and numbered: 39 and time 3.1102160000000367 seconds.
Data added for user number: 214 and numbered: 43 and time 3.7961109999999962 seconds.
Data added for user number: 721 and numbered: 37 and time 7.635591999999974 seconds.

Data added for user number: 967 and numbered: 57 and time 4.337237999999957 seconds.
Data added for user number: 722 and numbered: 64 and time 4.547370000000001 seconds.
Data added for user number: 473 and numbered: 60 and time 6.9151540000000296 seconds.
Data added for user number: 215 and numbered: 37 and time 7.281376000000023 seconds.
Data added for user number: 216 and numbered: 35 and time 1.1324280000000044 seconds.
Data added for user number: 968 and numbered: 46 and time 7.361927000000037 seconds.
Data added for user number: 723 and numbered: 54 and time 5.307280999999989 seconds.
Data added for user number: 969 and numbered: 63 and time 4.870380000000068 seconds.
Data added for user number: 217 and numbered: 43 and time 5.1501539999999295 seconds.
Data added for user number: 724 and numbered: 56 and time 5.4158259999999245 seconds.
Data added for user number: 474 and numbered: 63 and time 11.252724000000057 seconds.
Data added for user number: 218 and numbered: 47 and time 4.109535000000051 seconds.
Data added for user number: 219 and numbered: 47 and time 1.382618999999977 seconds.
Data added for user number: 970 and numbered: 61 and time 7.5608250000000226 seconds.
Data added for user number: 220 and numbered: 48 and time 3.9067079999999805 seconds.
Data added for user number: 971 and numbered: 41 and time 4.299731000000065 seconds.
Data added for user number: 475 and numbered: 38 and time 7.870401000000015 seconds.
Data added for user number: 221 and numbered: 51 and time 3.4182720000000018 seconds.
Data added for user number: 222 and numbered: 42 and time 1.7574369999999817 seconds.
Data added for user number: 725 and numbered: 55 and time 12.522575000000074 seconds.
Data added for user number: 972 and numbered: 61 and time 6.125526000000036 seconds.
Data added for user number: 476 and numbered: 52 and time 6.4824160000000575 seconds.
Data added for user number: 726 and numbered: 36 and time 4.856679999999983 seconds.
Data added for user number: 223 and numbered: 37 and time 7.089629999999943 seconds.
Data added for user number: 477 and numbered: 42 and time 3.545743000000016 seconds.
Data added for user number: 727 and numbered: 39 and time 3.0517469999999776 seconds.
Data added for user number: 973 and numbered: 61 and time 8.833548000000064 seconds.
Data added for user number: 478 and numbered: 51 and time 5.687717000000021 seconds.
Data added for user number: 974 and numbered: 63 and time 3.856916999999953 seconds.
Data added for user number: 728 and numbered: 60 and time 9.524271999999996 seconds.
Data added for user number: 224 and numbered: 64 and time 11.68228600000009 seconds.
Data added for user number: 479 and numbered: 59 and time 6.773063999999977 seconds.
Data added for user number: 975 and numbered: 41 and time 5.133591000000024 seconds.
Data added for user number: 225 and numbered: 47 and time 3.7811189999999897 seconds.
Data added for user number: 729 and numbered: 50 and time 5.399226999999996 seconds.
Data added for user number: 226 and numbered: 48 and time 2.0391169999999192 seconds.
Data added for user number: 480 and numbered: 43 and time 5.632150000000024 seconds.
Data added for user number: 481 and numbered: 35 and time 1.414303000000018 seconds.
Data added for user number: 976 and numbered: 40 and time 6.817060999999967 seconds.
Data added for user number: 482 and numbered: 46 and time 4.448504000000071 seconds.
Data added for user number: 730 and numbered: 64 and time 9.046555000000012 seconds.
Data added for user number: 977 and numbered: 56 and time 5.768444000000045 seconds.
Data added for user number: 731 and numbered: 45 and time 1.878645000000006 seconds.
Data added for user number: 227 and numbered: 51 and time 9.891517000000022 seconds.
Data added for user number: 483 and numbered: 46 and time 4.39672900000005 seconds.
Data added for user number: 978 and numbered: 43 and time 5.498911000000021 seconds.
Data added for user number: 732 and numbered: 52 and time 5.586404000000016 seconds.
Data added for user number: 979 and numbered: 41 and time 3.39664700000003 seconds.
Data added for user number: 228 and numbered: 53 and time 8.603469000000018 seconds.
Data added for user number: 733 and numbered: 39 and time 3.609162000000083 seconds.
Data added for user number: 484 and numbered: 63 and time 11.093240000000037 seconds.
Data added for user number: 980 and numbered: 50 and time 6.317821999999978 seconds.
Data added for user number: 485 and numbered: 57 and time 5.0271790000000465 seconds.
Data added for user number: 734 and numbered: 52 and time 9.353829000000019 seconds.
Data added for user number: 229 and numbered: 64 and time 10.397751999999969 seconds.
Data added for user number: 981 and numbered: 63 and time 5.427396999999928 seconds.
Data added for user number: 735 and numbered: 46 and time 5.198953999999958 seconds.
Data added for user number: 486 and numbered: 63 and time 7.361129000000005 seconds.
Data added for user number: 982 and numbered: 44 and time 5.666423000000009 seconds.
Data added for user number: 230 and numbered: 48 and time 8.32192299999997 seconds.
Data added for user number: 487 and numbered: 36 and time 4.3712059999999155 seconds.
Data added for user number: 983 and numbered: 36 and time 4.0175720000000865 seconds.
Data added for user number: 736 and numbered: 40 and time 6.368965000000003 seconds.
Data added for user number: 488 and numbered: 47 and time 2.9809490000000096 seconds.
Data added for user number: 737 and numbered: 37 and time 5.332604999999944 seconds.
Data added for user number: 489 and numbered: 41 and time 3.5734879999999976 seconds.
Data added for user number: 231 and numbered: 56 and time 8.57638499999996 seconds.
Data added for user number: 984 and numbered: 59 and time 6.558539999999994 seconds.
Data added for user number: 232 and numbered: 36 and time 3.632489000000078 seconds.
Data added for user number: 490 and numbered: 60 and time 5.11693600000001 seconds.
Data added for user number: 985 and numbered: 56 and time 5.436981999999944 seconds.
Data added for user number: 233 and numbered: 49 and time 3.6031809999999496 seconds.
Data added for user number: 738 and numbered: 38 and time 9.202203000000054 seconds.
Data added for user number: 491 and numbered: 56 and time 6.330526999999961 seconds.
Data added for user number: 234 and numbered: 46 and time 4.827402000000006 seconds.
Data added for user number: 739 and numbered: 56 and time 6.50658599999997 seconds.
Data added for user number: 986 and numbered: 57 and time 9.499276000000009 seconds.
Data added for user number: 235 and numbered: 46 and time 3.9475869999999986 seconds.
Data added for user number: 987 and numbered: 42 and time 3.059707000000003 seconds.
Data added for user number: 492 and numbered: 64 and time 9.384617000000048 seconds.
Data added for user number: 988 and numbered: 41 and time 2.6984390000000076 seconds.
Data added for user number: 740 and numbered: 48 and time 8.58313499999997 seconds.
Data added for user number: 236 and numbered: 64 and time 9.05474700000002 seconds.
Data added for user number: 493 and numbered: 59 and time 5.677558999999974 seconds.
Data added for user number: 989 and numbered: 60 and time 5.7072239999999965 seconds.
Data added for user number: 741 and numbered: 44 and time 3.6002429999999777 seconds.
Data added for user number: 742 and numbered: 53 and time 2.4316579999999703 seconds.
Data added for user number: 743 and numbered: 42 and time 1.320555000000013 seconds.
Data added for user number: 990 and numbered: 43 and time 5.144572999999923 seconds.
Data added for user number: 494 and numbered: 52 and time 8.334420000000023 seconds.
Data added for user number: 744 and numbered: 42 and time 5.053241000000071 seconds.
Data added for user number: 991 and numbered: 45 and time 5.646122999999989 seconds.
Data added for user number: 237 and numbered: 52 and time 12.666541000000052 seconds.
Data added for user number: 495 and numbered: 59 and time 6.04186900000002 seconds.
Data added for user number: 745 and numbered: 41 and time 5.59041000000002 seconds.
Data added for user number: 238 and numbered: 57 and time 5.046230999999921 seconds.
Data added for user number: 992 and numbered: 37 and time 6.51264900000001 seconds.

Data added for user number: 496 and numbered: 48 and time 4.742313999999965 seconds.
Data added for user number: 746 and numbered: 45 and time 5.79825900000003 seconds.
Data added for user number: 239 and numbered: 45 and time 5.684581999999978 seconds.
Data added for user number: 993 and numbered: 54 and time 6.656762000000072 seconds.
Data added for user number: 497 and numbered: 38 and time 5.475675999999908 seconds.
Data added for user number: 994 and numbered: 49 and time 2.3383910000000014 seconds.
Data added for user number: 240 and numbered: 63 and time 5.336600999999973 seconds.
Data added for user number: 498 and numbered: 43 and time 5.2790149999999585 seconds.
Data added for user number: 499 and numbered: 54 and time 1.6950949999999239 seconds.
Data added for user number: 747 and numbered: 56 and time 10.942287999999962 seconds.
Data added for user number: 995 and numbered: 39 and time 6.263200000000097 seconds.
Data added for user number: 241 and numbered: 63 and time 9.326930000000061 seconds.
Data added for user number: 242 and numbered: 35 and time 1.4958390000000463 seconds.
Data added for user number: 996 and numbered: 42 and time 5.845841999999948 seconds.
Data added for user number: 748 and numbered: 56 and time 7.258100000000013 seconds.
Data added for user number: 997 and numbered: 36 and time 1.524503999999979 seconds.
Data added for user number: 500 and numbered: 45 and time 10.03194499999995 seconds.
Data added for user number: 243 and numbered: 38 and time 4.170379000000025 seconds.
Data added for user number: 749 and numbered: 47 and time 5.37178700000004 seconds.
Data added for user number: 998 and numbered: 49 and time 5.675567999999998 seconds.
Data added for user number: 244 and numbered: 37 and time 4.75259200000005 seconds.
Data added for user number: 245 and numbered: 35 and time 1.130627000000004 seconds.
Data added for user number: 750 and numbered: 62 and time 5.919055999999955 seconds.
Data added for user number: 999 and numbered: 52 and time 6.165984999999978 seconds.
Data added for user number: 246 and numbered: 57 and time 5.01048000000003 seconds.
Data added for user number: 1000 and numbered: 39 and time 2.7795399999999972 seconds.
Data added for user number: 247 and numbered: 61 and time 2.5831410000000687 seconds.
Data added for user number: 248 and numbered: 52 and time 1.647246999999993 seconds.
Data added for user number: 249 and numbered: 40 and time 1.2852660000000924 seconds.
Data added for user number: 250 and numbered: 44 and time 1.4222389999999905 seconds.
Time taken: -995.937708

/home/mayuresh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:29: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead

In [14]:
new_dataframe

,Latitude,Longitude,Time,UTC time,User ID (anonymized),Venue ID (Foursquare),Venue category ID (Foursquare),Venue category name (Fousquare)
0,40.790606,-73.980521,1.353820e+09,Sun Nov 25 04:59:42 +0000 2012,1.0,4bc308db4cdfc9b639bf9621,4bf58dd8d48988d1e5941735,Other Great Outdoors
1,40.843364,-73.935256,1.335405e+09,Thu Apr 26 01:55:26 +0000 2012,1.0,4c05304339d476b0227b32a7,4bf58dd8d48988d1f1931735,General Entertainment
2,40.707156,-74.010733,1.353903e+09,Mon Nov 26 04:05:37 +0000 2012,1.0,4b6b179ef964a52032f22be3,4bf58dd8d48988d124941735,Office
3,40.640533,-73.977126,1.357704e+09,Wed Jan 09 03:53:46 +0000 2013,1.0,4de95fc6fa76fd1168b93af9,4bf58dd8d48988d103941735,Home (private)
4,40.646099,-73.902669,1.341837e+09,Mon Jul 09 12:26:13 +0000 2012,1.0,4b8f50d9f964a520365133e3,4bf58dd8d48988d1fd931735,Subway
...,...,...,...,...,...,...,...,...
49504,40.811990,-74.123855,1.360518e+09,Sun Feb 10 17:47:46 +0000 2013,250.0,4c9e2975d3c2b60c9053c8bc,4bf58dd8d48988d143941735,Breakfast Spot
49505,40.773847,-73.959489,1.336424e+09,Mon May 07 20:46:25 +0000 2012,250.0,4e6e8d177d8b6c5625c019bc,4bf58dd8d48988d1c1941735,Mexican Restaurant
49506,40.761397,-73.976986,1.338852e+09,Mon Jun 04 23:16:16 +0000 2012,250.0,4af5a46af964a520b5fa21e3,4bf58dd8d48988d18f941735,Art Museum
49507,40.747230,-74.000550,1.342011e+09,Wed Jul 11 12:44:22 +0000 2012,250.0,4c157c24a5eb76b0ab7ac3b7,4bf58dd8d48988d118951735,Food & Drink Shop
49508,40.798892,-74.118123,1.336606e+09,Wed May 09 23:29:09 +0000 2012,250.0,4c6fc1379375a0930fc70437,4bf58dd8d48988d103941735,Home (private)

In [15]:
#We need to sprt the data frame as per the time in ascending order
new_dataframe = new_dataframe.sort_values(by=['Time'], ascending=True)
new_dataframe

,Latitude,Longitude,Time,UTC time,User ID (anonymized),Venue ID (Foursquare),Venue category ID (Foursquare),Venue category name (Fousquare)
36672,40.740104,-73.989658,1.333476e+09,Tue Apr 03 18:03:00 +0000 2012,438.0,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck
735,40.740104,-73.989658,1.333476e+09,Tue Apr 03 18:03:00 +0000 2012,5.0,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck
12203,40.719762,-74.250014,1.333477e+09,Tue Apr 03 18:09:06 +0000 2012,316.0,4cb50d599c7ba35de0ef8706,4bf58dd8d48988d104941735,Medical Center
28582,40.826508,-73.950391,1.333477e+09,Tue Apr 03 18:16:10 +0000 2012,143.0,4b3a8e5df964a520d86925e3,4bf58dd8d48988d1fd931735,Subway
36666,40.750623,-73.990042,1.333477e+09,Tue Apr 03 18:24:02 +0000 2012,438.0,4cd03669c5b39eb043fb5a16,4bf58dd8d48988d111951735,Jewelry Store
...,...,...,...,...,...,...,...,...
3487,40.738699,-74.218211,1.360803e+09,Thu Feb 14 00:50:47 +0000 2013,517.0,4e0dcf4262e1d5a30cfa6cae,4bf58dd8d48988d1f9931735,Road
40195,40.721822,-73.993387,1.360803e+09,Thu Feb 14 00:53:28 +0000 2013,704.0,44e4a4f2f964a52065371fe3,4bf58dd8d48988d121941735,Bar
20341,40.753783,-74.214273,1.360803e+09,Thu Feb 14 00:54:42 +0000 2013,353.0,4bfec352daf9c9b64038f9ef,4bf58dd8d48988d16e941735,Fast Food Restaurant
28203,40.725848,-74.003993,1.360804e+09,Thu Feb 14 01:01:28 +0000 2013,646.0,4db12e95a86e63d21166092b,4bf58dd8d48988d1f9931735,Road
1681,40.748539,-73.986669,1.360804e+09,Thu Feb 14 01:04:49 +0000 2013,10.0,4576ba17f964a520ab3e1fe3,4bf58dd8d48988d11b941735,Bar

In [16]:
#Writing data frame to the file
new_dataframe.to_csv("newDataSet.tsv", sep="\t")

In [19]:
#Loading created file to see what is in it
df = pd.read_csv("newDataSet.tsv",sep='\t', engine="python")
df.drop(["Unnamed: 0"],axis=1, inplace=True)
df

,Latitude,Longitude,Time,UTC time,User ID (anonymized),Venue ID (Foursquare),Venue category ID (Foursquare),Venue category name (Fousquare)
0,40.740104,-73.989658,1.333476e+09,Tue Apr 03 18:03:00 +0000 2012,438.0,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck
1,40.740104,-73.989658,1.333476e+09,Tue Apr 03 18:03:00 +0000 2012,5.0,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck
2,40.719762,-74.250014,1.333477e+09,Tue Apr 03 18:09:06 +0000 2012,316.0,4cb50d599c7ba35de0ef8706,4bf58dd8d48988d104941735,Medical Center
3,40.826508,-73.950391,1.333477e+09,Tue Apr 03 18:16:10 +0000 2012,143.0,4b3a8e5df964a520d86925e3,4bf58dd8d48988d1fd931735,Subway
4,40.750623,-73.990042,1.333477e+09,Tue Apr 03 18:24:02 +0000 2012,438.0,4cd03669c5b39eb043fb5a16,4bf58dd8d48988d111951735,Jewelry Store
...,...,...,...,...,...,...,...,...
49504,40.738699,-74.218211,1.360803e+09,Thu Feb 14 00:50:47 +0000 2013,517.0,4e0dcf4262e1d5a30cfa6cae,4bf58dd8d48988d1f9931735,Road
49505,40.721822,-73.993387,1.360803e+09,Thu Feb 14 00:53:28 +0000 2013,704.0,44e4a4f2f964a52065371fe3,4bf58dd8d48988d121941735,Bar
49506,40.753783,-74.214273,1.360803e+09,Thu Feb 14 00:54:42 +0000 2013,353.0,4bfec352daf9c9b64038f9ef,4bf58dd8d48988d16e941735,Fast Food Restaurant
49507,40.725848,-74.003993,1.360804e+09,Thu Feb 14 01:01:28 +0000 2013,646.0,4db12e95a86e63d21166092b,4bf58dd8d48988d1f9931735,Road
49508,40.748539,-73.986669,1.360804e+09,Thu Feb 14 01:04:49 +0000 2013,10.0,4576ba17f964a520ab3e1fe3,4bf58dd8d48988d11b941735,Bar